
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: rollout-template
  namespace: duyaccel-dev
spec:
  params:
    - name: repo-url
    - name: command
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: rollout-green-pipeline-
        namespace: duyaccel-dev
      spec:
        params:
          - name: repo-url
            value: "$(tt.params.repo-url)"  
          - name: command
            value: "$(tt.params.command)"
        pipelineSpec:
          tasks:
            - name: pull-config-repo
              params:
                - name: repo-url
                  value: "$(params.repo-url)"
              taskRef:
                name: pull-repo
            - name: rollout
              params:
                - name: command
                  value: "$(params.command)"
              taskRef:
                name: exec-kubectl
#serviceAccountName: pipeline-runner
--- 
