apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: rollout-template
  namespace: duyaccel-dev
spec:
  params:
    - name: repo-url
    - name: workdir
    - name: command
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: rollout-green-pipeline-
        namespace: duyaccel-dev
      spec:
        params:
          - name: repo-url
            value: "$(tt.params.repo-url)"  
          - name: workdir 
            value: "$(tt.params.workdir)"
          - name: command
            value: "$(tt.params.command)"
        pipelineRef:
          - name: rollout-pipeline
        workspaces:
          - name: default
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteMany
                resources:
                  requests:
                    storage: 300Mi

      #serviceAccountName: pipeline-runner
--- 
