apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: pull-repo
  namespace: duyaccel-dev
spec:
  params:
    - name: repo-url
      type: string
      description: git repo url to pull from

  steps:
    - name: pull-repository
      image: alpine:3.20.3
      script: |
        #!/bin/sh 
        apk add --no-cache git 
        git clone $(params.repo-url) /manifest
        cd /manifest
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: exec-kubectl
  namespace: duyaccel-dev
spec:
  params:
    - name: command
      type: string
      description: command to execute
  steps:
    - name: exec-cmd
      image: duyaccel/admin:k8s.14-11-2024.9h50p
      script: |
        #!/bin/sh 
        $(params.command)
---
