apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: alert-listener
  namespace: duyaccel-dev
spec:
  serviceAccountName: event-listener
  triggers:
    - name: rollout
      interceptors: 
        - ref:
            name: cel
          params:
            - name: filter
              value: "body.commonLabels.action == 'rollout'"

      bindings: 
        - name: repo-url
          value: "https://github.com/DuyAccel/blue-green-cd.git"
        - name: command
          value: "./rollout.sh"
       
      template:
        ref: rollout-template

    #    - name: rollback
    #      interceptors: dont-know
--- 
