apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kubectl
  namespace: duyaccel-dev
spec:
  params:
    - name: command
      type: string
      description: command to execute
  workspaces:
    - name: default
      mountPath: /workspace

  steps:
    - name: exec-cmd
      image: duyaccel/admin:k8s.14-11-2024.9h50p
      script: |
        #!/bin/sh 
        cd /workspace/new-ver 
        $(params.command) old-ver

        echo "clean up workspace"
        cd /workspace
        rm -rf new-ver old-ver
---
