apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kubectl
  namespace: duyaccel-dev
spec:
  params:
    - name: command
      type: string
      description: command to execute
    - name: old-version
      type: string
      default: 'stable'
      description: name of the old version
    - name: new-version
      type: string
      default: ''
      description: name of the new version
  workspaces:
    - name: default
      mountPath: /workspace

  steps:
    - name: exec-cmd
      image: duyaccel/admin:k8s.14-11-2024.9h50p
      script: |
        #!/bin/sh 
        cd /workspace/$(params.workdir)
        $(params.command) $(params.new-version) $(params.old-version)
---
