apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: gitpull
  namespace: duyaccel-dev
spec:
  params:
    - name: repo-url
      type: string
      description: git repo url to pull from
    - name: old-version
      type: string
      description: name of the old version
    - name: new-version
      type: string
      description: name of the new version

  workspaces:
    - name: default
      mountPath: /workspace

  steps:
    - name: pull-repository
      image: alpine:3.20.3
      script: |
        #!/bin/sh 
        apk add --no-cache git 
        git clone $(params.repo-url) \
          --branch $(params.old-version) \
          --single-branch \
          /workspace/$(params.old-version)

        git clone $(params.repo-url) \
          --branch $(params.new-version) \
          --single-branch \
          /workspace/$(params.new-version)
        
        ls -l 
        
---
