apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: blue-green-template
  namespace: duyaccel-dev
spec:
  params:
    - name: repo-url
    - name: command
    - name: old-version
    - name: new-version
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generate-name: rollout-green-pipeline
        namespace: duyaccel-dev
      spec:
        params:
          - name: repo-url
            value: "$(tt.params.repo-url)"  
          - name: command
            value: "$(tt.params.command)"
          - name: old-version
            value: "$(tt.params.old-version)"
          - name: new-version
            value: "$(tt.params.new-version)"
        pipelineRef:
          name: rollout-pipeline
        workspaces:
          - name: default
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteMany
                resources:
                  requests:
                    storage: 300Mi
        serviceAccountName: pipeline-runner
--- 
