apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: demo-alert
  namespace: duyaccel-dev

spec:
  route:
    receiver: 'cluster-listener'
    groupBy: [namespace, app]
    groupInterval: 5m
    repeatInterval: 10m

  receivers:
    - name: cluster-listener
      webhookConfigs:
        - url: https://discord.com/api/webhooks/1308467362005258251/AbihwXZ3fafa19Zwd0x1E_naqd9CvH2c_Nb6uq3Hrp4ZIvUgBn2aRRGd_Zkow9SW-Hhm
          sendResolved: false
        - url: http://el-alert-listener.duyaccel-dev.svc.cluster.local:8080
          sendResolved: false
---
