apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: demo-rules
  namespace: duyaccel-dev
  labels:
    app: demo
    release: base
spec:
  groups:
    - name: Blue/Green monitoring
      rules:
        - alert: ContainersUsingTooMuchCPU
          for: 1m
          expr: avg(container_cpu_usage_seconds_total{pod=~"{{NEW_DEPLOY}}.*"}) > 0.07
          labels:
            severity: critical
            namespace: duyaccel-dev
            version: {{VERSION}}
            action: rollback
          annotations:
            summary: Canceling GREEN deployment.
            message: |-
              Containers is using too much CPU resource. 
              This behavior is not desire-statge and may lead to problems.
              Rollback event will be trigger to cancel the GREEN deployment.

        - alert: ContainersUsingTooMuchMemory
          for: 1m
          expr: avg(container_memory_working_set_bytes{pod=~"{{NEW_DEPLOY}}.*"})/(2^20) > 10
          labels:
            severity: critical
            namespace: duyaccel-dev
            version: {{VERSION}}
            action: rollback
          annotations:
            summary: Canceling GREEN deployment.
            message: |-
              Containers is using too much Memory resource. 
              This behavior is not desire-statge and may lead to problems.
              Rollback event will be trigger to cancel the GREEN deployment.


        - alert: PodLowAvailability
          for: 1m
          expr: avg(kube_pod_container_status_ready{pod=~'{{NEW_DEPLOY}}.*'}) < 0.5
          labels:
            severity: critical
            namespace: duyaccel-dev
            version: {{VERSION}}
            action: rollback
          annotations:
            summary: Canceling GREEN deployment.
            message: |-
              Too many pod are not ready.
              This behavior is not desire-statge and may lead to problems.
              Rollback event will be trigger to cancel the GREEN deployment.

        - alert: HttpResponseFailed
          for: 1m
          #          expr: sum(rate(haproxy_backend_http_responses_total{code!='200', proxy=~'duyaccel-dev_demo-svc_main'}[1m])) > 0.2
          expr: sum(rate(haproxy_backend_http_responses_total{code!='200', proxy=~'.*{{OLD_DEPLOY}}.*'}[1m])) > 0.2
          labels:
            severity: critical
            namespace: duyaccel-dev 
            version: {{VERSION}}
            action: rollback
          annotations:
            summary: Canceling GREEN deployment.
            message: |-
              Spotted too many failure respone in a short term
              This behavior is not desire-statge and may lead to problems.
              Rollback event will be trigger to cancel the GREEN deployment.

        - alert: StableDeployment
          for:  2m 
          expr: count(kube_pod_info{pod=~'{{OLD_DEPLOY}}.*'}) * sum(sum_over_time(ALERTS{action='rollback', alertstate='firing', version='{{VERSION}}'}[2m]) or vector(0)) < 1
          labels:
            severity: warning
            namespace: duyaccel-dev
            version: {{VERSION}}
            action: rollout
          annotations:
            summary: Routing traffic to GREEN deployment.
            message: |-
              The system was stable for a long time. This is what we desired.
              Routing traffic event will be trigger to rollout new version.

---
