apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kubectl
  namespace: duyaccel-dev
spec:
  params:
    - name: workdir
      type: string 
      description: name of working directory

    - name: command
      type: string
      description: command to execute
    
  workspaces:
    - name: default

  steps:
    - name: exec-cmd
      image: duyaccel/admin:k8s.14-11-2024.9h50p
      script: |
        #!/bin/sh 
        cd /workspace/$(params.workdir)
        $(params.command)
---
