apiVersion: v1
kind: PersistentVolume
metadata:
  generateName: pv-500mi-
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /home/WORK/kubernetes/VMs/nfs
    server: 192.168.122.1

