apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deploy
spec:
  template:
    metadata:
      labels:
        ver: green
    spec:
      containers:
      - name: demo-web
        $patch: delete
      - name: demo-stress
        image: duyaccel/stress:cpu-ram.12112024.22h.20p
        imagePullPolicy: IfNotPresent
