########################################
#                                      #
#         OVER-USE MEMORY/CPU          #
#                                      #
########################################


apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: duyaccel-dev
resources:
  - ../../../base
  - alert/alertmanager-config.yaml
  - alert/haproxy.yaml
  - alert/prometheus-rule.yaml
  - ingress.yaml

namePrefix: green-

patches:
  - path: deployment.yaml

