
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: demo-alert
  namespace: duyaccel-dev

spec:
  route:
    receiver: 'ansible.eda'
    groupBy: [namespace, app]

  receivers:
    - name: test-webhook
      webhookConfigs:
      - url: http://localhost:5000
