apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: demo-alert
  namespace: duyaccel-dev

spec:
  route:
    groupBy: [namespace, app]
    groupInterval: 5m
    repeatInterval: 10m
    routes:
      - matchers:
          - namespace: duyaccel-dev
          - app: demo
        receiver: 'cluster-listener'

  receivers:
    - name: cluster-listener
      webhookConfigs:
        - url: https://webhook.site/ff68ee9f-c5c4-4fa6-8436-7f7257c68390
          sendResolved: false
        - url: http://el-alert-listener.duyaccel-dev.svc.cluster.local:8080
          sendResolved: false
---
