apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: demo-alert
  namespace: duyaccel-dev

spec:
  route:
    receiver: 'webhook'
    groupBy: [namespace, app]
    groupInterval: 5m
    repeatInterval: 10m

  receivers:
    - name: webhook
      webhookConfigs:
        - url: https://webhook.site/ff68ee9f-c5c4-4fa6-8436-7f7257c68390
          sendResolved: false
        - url: http://el-alert-listener.duyaccel-dev.svc.cluster.local:8080
          sendResolved: false
---
