apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: demo-rules
  namespace: duyaccel-dev
  labels:
    app: demo
    release: base
spec:
  groups:
    - name: Blue/Green monitoring
      rules:
        - alert: PodLowAvailability
          for: 1m
          expr: avg(kube_pod_container_status_ready{pod=~'{{ .NewDeploy }}.*'}) < 0.5
          labels:
            severity: critical
            namespace: duyaccel-dev
            curr_version: {{ .OldVersion }}
            new_version: {{ .NewVersion }}
            state: NotReady
          annotations:
            summary: Canceling GREEN deployment.
            message: |-
              Too many pod are not ready.
              This behavior is not desire-statge and may lead to problems.
              Rollback event will be trigger to cancel the GREEN deployment.

        - alert: ContainersUsingTooMuchCPU
          for: 1m
          expr: avg(container_cpu_usage_seconds_total{pod=~"{{ .NewDeploy }.*"}}) > 0.2
          labels:
            severity: critical
            namespace: duyaccel-dev
            curr_version: {{ .OldVersion }}
            new_version: {{ .NewVersion }}
            state: NotStable
          annotations:
            summary: Canceling GREEN deployment.
            message: |-
              Containers is using too much CPU resource. 
              This behavior is not desire-statge and may lead to problems.
              Rollback event will be trigger to cancel the GREEN deployment.

        - alert: ContainersUsingTooMuchMemory
          for: 1m
          expr: avg(container_memory_working_set_bytes{pod=~"{{ .OldDeploy }}.*"})/(2^20) > 10
          labels:
            severity: critical
            namespace: duyaccel-dev
            curr_version: {{ .OldVersion }}
            new_version: {{ .NewVersion }}
            state: NotStable
          annotations:
            summary: Canceling GREEN deployment.
            message: |-
              Containers is using too much Memory resource. 
              This behavior is not desire-statge and may lead to problems.
              Rollback event will be trigger to cancel the GREEN deployment.

        - alert: HttpResponseFailed
          for: 1m
          expr: sum(rate(haproxy_backend_http_responses_total{code!='200', proxy=~'.*{{ .)ldDeploy }}.*'}[1m])) > 0.2
          labels:
            severity: critical
            namespace: duyaccel-dev 
            curr_version: {{ .OldVersion }}
            new_version: {{ .NewVersion }}
            state: NotStable
          annotations:
            summary: Canceling GREEN deployment.
            message: |-
              Spotted too many failure respone in a short term
              This behavior is not desire-statge and may lead to problems.
              Rollback event will be trigger to cancel the GREEN deployment.

        - alert: StableDeployment
          for:  2m 
          expr: count(kube_pod_info{pod=~'{{ .OldDeploy }}.*'}) * sum(sum_over_time(ALERTS{action='rollback', alertstate='firing', version='{{ .Version }}'}[2m]) or vector(0)) < 1
          labels:
            severity: warning
            namespace: duyaccel-dev
            curr_version: {{ .OldVersion }}
            new_version: {{ .NewVersion }}
            state: Stable
          annotations:
            summary: Routing traffic to GREEN deployment.
            message: |-
              The system was stable for a long time. This is what we desired.
              Routing traffic event will be trigger to rollout new version.

---
